report_used_space probe added
rucio/probes pull request #52
Opened 2021-02-12 16:26 UTC by FernandoGarzon

2021-02-12 20:59 UTC, ericvaandering requested changes

2021-02-12 20:59 UTC, ericvaandering commented on cms/check_report_used_space
> +                attributes = list_rse_attributes(rse['id'])
The attributes don't change. Should be in the outer loop, not this one.

2021-02-12 20:59 UTC, ericvaandering commented on cms/check_report_used_space
> +                    country = 'UNKWON'
Spell it correctly

2021-02-12 20:59 UTC, ericvaandering commented on cms/check_report_used_space
> +                    country = 'UNKWON'
You can also use a dictionary "get" method to reduce these four lines to one

2021-02-12 20:59 UTC, ericvaandering commented on cms/check_report_used_space
> +                type_ = result[0]
Good job not using type, but why not rse_type instead of type_

2021-02-12 22:18 UTC, ericvaandering commented
@dchristidis Can you merge this one too? But I think this may be of broader use to others as well.

2021-03-01 18:29 UTC, dchristidis reviewed
I have reviewed your PR. Once again, my comments are mostly cosmetic.

@ericvaandering, if you don’t think they are necessary, please approve the PR and I’ll merge it immediately.

2021-03-01 18:29 UTC, dchristidis commented on cms/check_report_used_space
> +# - Fernando Garzon, <oscar.fernando.garzon.miguez.ch> 2020
Please replace the licence block and consistently format the authors.

2021-03-01 18:29 UTC, dchristidis commented on cms/check_report_used_space
> +import unicodedata
These two aren’t used.

2021-03-01 18:29 UTC, dchristidis commented on cms/check_report_used_space
> +from rucio.db.sqla.session import BASE, get_session
`BASE` can be removed.

2021-03-01 18:29 UTC, dchristidis commented on cms/check_report_used_space
> +    schema = BASE.metadata.schema + '.'
This is no longer needed.

2021-03-01 18:29 UTC, dchristidis commented on cms/check_report_used_space
> +        status = OK
`status` isn’t actually used. Consider either explicitly calling `sys.exit()` at the end or removing this.

2021-03-01 18:29 UTC, dchristidis commented on cms/check_report_used_space
> +            limits = get_rse_usage(rse['id'])
I am under the impression that the name `limits` is misleading.

2021-03-01 18:29 UTC, dchristidis commented on cms/check_report_used_space
> +                rse_type = result[0]
These should be moved outside of the loop: they are the same per RSE, no need to re-fetch them per RSE usage.

2021-03-01 18:29 UTC, dchristidis commented on cms/check_report_used_space
> +                rse_type = result[0]
I have a preference for using `rucio.core.rse.get_rse`, which allows you to get rid of the database-related imports. If you disagree, at least use `.scalar()` and combine everything in a single statement.

2021-03-01 18:45 UTC, ericvaandering commented
> I have reviewed your PR. Once again, my comments are mostly cosmetic.
> 
> @ericvaandering, if you don’t think they are necessary, please approve the PR and I’ll merge it immediately.

These are all good and @FernandoGarzon should address them.

2021-03-02 22:26 UTC, FernandoGarzon commented
@dchristidis all your comments were taken into account. Thanks.

2021-03-02 22:35 UTC, ericvaandering commented
Looks good. Merging

2021-03-02 22:35 UTC, merged