free space probe added
rucio/probes pull request #57
Opened 2021-03-12 17:14 UTC by FernandoGarzon

2021-03-12 20:20 UTC, ericvaandering commented on cms/check_free_space
> +from rucio.core.rse import list_rses, get_rse_usage
If you can use rucio.api.rse functions that would be even better. There is often a 1:1 map.

2021-03-12 20:20 UTC, ericvaandering commented on cms/check_free_space
> +            if (rucio_used == None) or ( static_used == None ):
No spaces in the 2nd half of the line

2021-03-12 20:20 UTC, ericvaandering commented on cms/check_free_space
> +            if (rucio_used == None) or ( static_used == None ):
Also comparisons with None should use "is" not "==" (research why).

2021-03-15 17:56 UTC, dchristidis reviewed
Some remarks from `pycodestyle`:
```
cms/check_free_space:40:54: E251 unexpected spaces around keyword / parameter equals
cms/check_free_space:40:56: E251 unexpected spaces around keyword / parameter equals
cms/check_free_space:45:39: E203 whitespace before ','
cms/check_free_space:48:40: E203 whitespace before ','
cms/check_free_space:50:41: E201 whitespace after '('
cms/check_free_space:50:61: E202 whitespace before ')'
cms/check_free_space:53:18: E111 indentation is not a multiple of four
cms/check_free_space:53:18: E117 over-indented
cms/check_free_space:55:62: E225 missing whitespace around operator
cms/check_free_space:56:5: E722 do not use bare 'except'
cms/check_free_space:57:14: E211 whitespace before '('
```

2021-06-09 15:54 UTC, ericvaandering requested changes
Same comment here. Please use Prometheus

2021-07-06 16:26 UTC, ericvaandering requested changes

2021-07-06 16:26 UTC, ericvaandering commented on cms/check_free_space
> +                monitor.record_gauge(stat='judge.free_space.%s' % rse['rse'], value=free_space)
You still are not using prometheus as requested. Why not?

2021-07-08 19:47 UTC, merged