check_number_of_missing_files_per_rse ported to Prometheus
rucio/probes pull request #73
Opened 2021-12-21 21:02 UTC by FernandoGarzon

2021-12-21 21:26 UTC, ericvaandering requested changes

2021-12-21 21:26 UTC, ericvaandering commented on cms/check_number_of_missing_files_per_rse
> +        if PROM_SERVERS:
No need to push things twice. At the end of the probe is fine.

2021-12-21 21:26 UTC, ericvaandering commented on cms/check_number_of_missing_files_per_rse
> +            prom_labels = {'rse': rse}
If you look here: https://github.com/dmwm/rucio-flux/blob/main/infrastructure/statsd/statsd-prometheus-mapping.yaml you'll see that the prometheus label is dst_rse not rse. We should keep it the same.

Same for the second gauge, of course.

2021-12-21 21:26 UTC, ericvaandering commented on cms/check_number_of_missing_files_per_rse
> +    #status = OK
I don't think there is any reason to change the exit codes from what they originally were

2022-01-26 15:33 UTC, ericvaandering commented
@FernandoGarzon it looks like you addressed all the comments. Can you confirm?

2022-01-26 16:33 UTC, FernandoGarzon commented
I did, @ericvaandering

2022-03-15 21:15 UTC, merged