Rule status vs time
rucio/probes pull request #98
Opened 2022-05-06 18:44 UTC by FernandoGarzon

2022-05-12 14:59 UTC, ericvaandering requested changes

2022-05-12 14:59 UTC, ericvaandering commented on cms/check_rule_counts
> +            prom_labels = {'age': a_name.split('_')[1]}
This seems to be a repeat (with no change in intermediate value of the code on 217 and 202 (a_name and extra_prom_labels are not changing)

2022-05-12 14:59 UTC, ericvaandering commented on cms/check_rule_counts
>              prom_labels.update(extra_prom_labels)
Same

2022-05-12 14:59 UTC, ericvaandering commented on cms/check_rule_counts
> +            prom_labels = {'age': a_name.split('_')[1]}
Same

2022-05-12 14:59 UTC, ericvaandering commented on cms/check_rule_counts
> +    sys.exit(OK)
Please have a carriage return at the end of the file

2022-05-12 18:35 UTC, FernandoGarzon commented
Updated. Unnecessary dictionaries removed.

2022-05-18 18:42 UTC, FernandoGarzon commented
Counts of state of rules and locks by activity added. No further changes are intended to be added to this probe.

2022-06-27 20:22 UTC, merged